# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.19.0"
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/ikamensh/flynt
    rev: "1.0.1"
    hooks:
      - id: flynt
        args: [--line-length, "120"]

  - repo: https://github.com/PyCQA/autoflake # configuration in pyproject.toml
    rev: "v2.3.1"
    hooks:
      - id: autoflake
        args: []

  # isort and black should be after other python hooks
  - repo: https://github.com/pycqa/isort # configuration in pyproject.toml
    rev: "5.13.2"
    hooks:
      - id: isort
        name: isort (python)

  # isort and black should be after other python hooks, black should be after isort
  - repo: https://github.com/psf/black # configuration in pyproject.toml
    rev: "24.10.0"
    hooks:
      - id: black

  # this should be the last hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace # trims trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      - id: check-json # checks syntax of json files
      - id: check-added-large-files # prevent giant files from being committed
      - id: fix-encoding-pragma # removes "# -*- coding: utf-8 -*-" from python files (since we only support python 3)
        args: [--remove]
      - id: check-merge-conflict # check for files that contain merge conflict strings
